name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  CMake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      run: make cmake

    - name: Build
      shell: bash
      run: make build

    - name: Test
      shell: bash
      run: make test

