name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  CMake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure submodules
      shell: bash
      run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Configure CMake
      shell: bash
      run: make cmake

    - name: Build
      shell: bash
      run: make build

