name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  CMake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install GTest
      shell: bash
      run: |
        git clone https://github.com/google/googletest.git
        mkdir -p /tmp/googletest/build && cd $_ && \
        cmake .. && \
        make && \
        make install && \
        cd /

    - name: Configure CMake
      shell: bash
      run: make cmake

    - name: Build
      shell: bash
      run: make build

    - name: Test
      shell: bash
      run: make test

